:- module(io_pairs, [io_pair/3]).

% io_pair(Id, Sentence, ExpectedSpecRequirements).
io_pair(1, "A cat runs through the city at sunset.", expected([subjects(['cat']),actions(['runs']),location(city),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(2, "A tiger flies through the ocean at storm.", expected([subjects(['tiger']),actions(['flies']),location(ocean),weather(storm),style(vector),min_scene_count(5)])).
io_pair(3, "A astronaut crosses through the palace at rain.", expected([subjects(['astronaut']),actions(['crosses']),location(palace),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(4, "A train escapes through the mountains at snowy.", expected([subjects(['train']),actions(['escapes']),location(mountains),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(5, "A ship dances through the moon at clear.", expected([subjects(['ship']),actions(['dances']),location(moon),weather(clear),style(vector),min_scene_count(5)])).
io_pair(6, "A bird jumps through the space at night.", expected([subjects(['bird']),actions(['jumps']),location(space),weather(night),style(rendered),min_scene_count(5)])).
io_pair(7, "A dancer approaches through the forest at sunset.", expected([subjects(['dancer']),actions(['approaches']),location(forest),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(8, "A robot launches through the desert at storm.", expected([subjects(['robot']),actions(['launches']),location(desert),weather(storm),style(vector),min_scene_count(5)])).
io_pair(9, "A traveller runs through the harbour at rain.", expected([subjects(['traveller']),actions(['runs']),location(harbour),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(10, "A pilot flies through the village at snowy.", expected([subjects(['pilot']),actions(['flies']),location(village),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(11, "A cat crosses through the city at clear.", expected([subjects(['cat']),actions(['crosses']),location(city),weather(clear),style(vector),min_scene_count(5)])).
io_pair(12, "A tiger escapes through the ocean at night.", expected([subjects(['tiger']),actions(['escapes']),location(ocean),weather(night),style(rendered),min_scene_count(5)])).
io_pair(13, "A astronaut dances through the palace at sunset.", expected([subjects(['astronaut']),actions(['dances']),location(palace),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(14, "A train jumps through the mountains at storm.", expected([subjects(['train']),actions(['jumps']),location(mountains),weather(storm),style(vector),min_scene_count(5)])).
io_pair(15, "A ship approaches through the moon at rain.", expected([subjects(['ship']),actions(['approaches']),location(moon),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(16, "A bird launches through the space at snowy.", expected([subjects(['bird']),actions(['launches']),location(space),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(17, "A dancer runs through the forest at clear.", expected([subjects(['dancer']),actions(['runs']),location(forest),weather(clear),style(vector),min_scene_count(5)])).
io_pair(18, "A robot flies through the desert at night.", expected([subjects(['robot']),actions(['flies']),location(desert),weather(night),style(rendered),min_scene_count(5)])).
io_pair(19, "A traveller crosses through the harbour at sunset.", expected([subjects(['traveller']),actions(['crosses']),location(harbour),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(20, "A pilot escapes through the village at storm.", expected([subjects(['pilot']),actions(['escapes']),location(village),weather(storm),style(vector),min_scene_count(5)])).
io_pair(21, "A cat dances through the city at rain.", expected([subjects(['cat']),actions(['dances']),location(city),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(22, "A tiger jumps through the ocean at snowy.", expected([subjects(['tiger']),actions(['jumps']),location(ocean),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(23, "A astronaut approaches through the palace at clear.", expected([subjects(['astronaut']),actions(['approaches']),location(palace),weather(clear),style(vector),min_scene_count(5)])).
io_pair(24, "A train launches through the mountains at night.", expected([subjects(['train']),actions(['launches']),location(mountains),weather(night),style(rendered),min_scene_count(5)])).
io_pair(25, "A ship runs through the moon at sunset.", expected([subjects(['ship']),actions(['runs']),location(moon),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(26, "A bird flies through the space at storm.", expected([subjects(['bird']),actions(['flies']),location(space),weather(storm),style(vector),min_scene_count(5)])).
io_pair(27, "A dancer crosses through the forest at rain.", expected([subjects(['dancer']),actions(['crosses']),location(forest),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(28, "A robot escapes through the desert at snowy.", expected([subjects(['robot']),actions(['escapes']),location(desert),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(29, "A traveller dances through the harbour at clear.", expected([subjects(['traveller']),actions(['dances']),location(harbour),weather(clear),style(vector),min_scene_count(5)])).
io_pair(30, "A pilot jumps through the village at night.", expected([subjects(['pilot']),actions(['jumps']),location(village),weather(night),style(rendered),min_scene_count(5)])).
io_pair(31, "A cat approaches through the city at sunset.", expected([subjects(['cat']),actions(['approaches']),location(city),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(32, "A tiger launches through the ocean at storm.", expected([subjects(['tiger']),actions(['launches']),location(ocean),weather(storm),style(vector),min_scene_count(5)])).
io_pair(33, "A astronaut runs through the palace at rain.", expected([subjects(['astronaut']),actions(['runs']),location(palace),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(34, "A train flies through the mountains at snowy.", expected([subjects(['train']),actions(['flies']),location(mountains),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(35, "A ship crosses through the moon at clear.", expected([subjects(['ship']),actions(['crosses']),location(moon),weather(clear),style(vector),min_scene_count(5)])).
io_pair(36, "A bird escapes through the space at night.", expected([subjects(['bird']),actions(['escapes']),location(space),weather(night),style(rendered),min_scene_count(5)])).
io_pair(37, "A dancer dances through the forest at sunset.", expected([subjects(['dancer']),actions(['dances']),location(forest),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(38, "A robot jumps through the desert at storm.", expected([subjects(['robot']),actions(['jumps']),location(desert),weather(storm),style(vector),min_scene_count(5)])).
io_pair(39, "A traveller approaches through the harbour at rain.", expected([subjects(['traveller']),actions(['approaches']),location(harbour),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(40, "A pilot launches through the village at snowy.", expected([subjects(['pilot']),actions(['launches']),location(village),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(41, "A cat runs through the city at clear.", expected([subjects(['cat']),actions(['runs']),location(city),weather(clear),style(vector),min_scene_count(5)])).
io_pair(42, "A tiger flies through the ocean at night.", expected([subjects(['tiger']),actions(['flies']),location(ocean),weather(night),style(rendered),min_scene_count(5)])).
io_pair(43, "A astronaut crosses through the palace at sunset.", expected([subjects(['astronaut']),actions(['crosses']),location(palace),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(44, "A train escapes through the mountains at storm.", expected([subjects(['train']),actions(['escapes']),location(mountains),weather(storm),style(vector),min_scene_count(5)])).
io_pair(45, "A ship dances through the moon at rain.", expected([subjects(['ship']),actions(['dances']),location(moon),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(46, "A bird jumps through the space at snowy.", expected([subjects(['bird']),actions(['jumps']),location(space),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(47, "A dancer approaches through the forest at clear.", expected([subjects(['dancer']),actions(['approaches']),location(forest),weather(clear),style(vector),min_scene_count(5)])).
io_pair(48, "A robot launches through the desert at night.", expected([subjects(['robot']),actions(['launches']),location(desert),weather(night),style(rendered),min_scene_count(5)])).
io_pair(49, "A traveller runs through the harbour at sunset.", expected([subjects(['traveller']),actions(['runs']),location(harbour),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(50, "A pilot flies through the village at storm.", expected([subjects(['pilot']),actions(['flies']),location(village),weather(storm),style(vector),min_scene_count(5)])).
io_pair(51, "A cat crosses through the city at rain.", expected([subjects(['cat']),actions(['crosses']),location(city),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(52, "A tiger escapes through the ocean at snowy.", expected([subjects(['tiger']),actions(['escapes']),location(ocean),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(53, "A astronaut dances through the palace at clear.", expected([subjects(['astronaut']),actions(['dances']),location(palace),weather(clear),style(vector),min_scene_count(5)])).
io_pair(54, "A train jumps through the mountains at night.", expected([subjects(['train']),actions(['jumps']),location(mountains),weather(night),style(rendered),min_scene_count(5)])).
io_pair(55, "A ship approaches through the moon at sunset.", expected([subjects(['ship']),actions(['approaches']),location(moon),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(56, "A bird launches through the space at storm.", expected([subjects(['bird']),actions(['launches']),location(space),weather(storm),style(vector),min_scene_count(5)])).
io_pair(57, "A dancer runs through the forest at rain.", expected([subjects(['dancer']),actions(['runs']),location(forest),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(58, "A robot flies through the desert at snowy.", expected([subjects(['robot']),actions(['flies']),location(desert),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(59, "A traveller crosses through the harbour at clear.", expected([subjects(['traveller']),actions(['crosses']),location(harbour),weather(clear),style(vector),min_scene_count(5)])).
io_pair(60, "A pilot escapes through the village at night.", expected([subjects(['pilot']),actions(['escapes']),location(village),weather(night),style(rendered),min_scene_count(5)])).
io_pair(61, "A cat dances through the city at sunset.", expected([subjects(['cat']),actions(['dances']),location(city),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(62, "A tiger jumps through the ocean at storm.", expected([subjects(['tiger']),actions(['jumps']),location(ocean),weather(storm),style(vector),min_scene_count(5)])).
io_pair(63, "A astronaut approaches through the palace at rain.", expected([subjects(['astronaut']),actions(['approaches']),location(palace),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(64, "A train launches through the mountains at snowy.", expected([subjects(['train']),actions(['launches']),location(mountains),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(65, "A ship runs through the moon at clear.", expected([subjects(['ship']),actions(['runs']),location(moon),weather(clear),style(vector),min_scene_count(5)])).
io_pair(66, "A bird flies through the space at night.", expected([subjects(['bird']),actions(['flies']),location(space),weather(night),style(rendered),min_scene_count(5)])).
io_pair(67, "A dancer crosses through the forest at sunset.", expected([subjects(['dancer']),actions(['crosses']),location(forest),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(68, "A robot escapes through the desert at storm.", expected([subjects(['robot']),actions(['escapes']),location(desert),weather(storm),style(vector),min_scene_count(5)])).
io_pair(69, "A traveller dances through the harbour at rain.", expected([subjects(['traveller']),actions(['dances']),location(harbour),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(70, "A pilot jumps through the village at snowy.", expected([subjects(['pilot']),actions(['jumps']),location(village),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(71, "A cat approaches through the city at clear.", expected([subjects(['cat']),actions(['approaches']),location(city),weather(clear),style(vector),min_scene_count(5)])).
io_pair(72, "A tiger launches through the ocean at night.", expected([subjects(['tiger']),actions(['launches']),location(ocean),weather(night),style(rendered),min_scene_count(5)])).
io_pair(73, "A astronaut runs through the palace at sunset.", expected([subjects(['astronaut']),actions(['runs']),location(palace),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(74, "A train flies through the mountains at storm.", expected([subjects(['train']),actions(['flies']),location(mountains),weather(storm),style(vector),min_scene_count(5)])).
io_pair(75, "A ship crosses through the moon at rain.", expected([subjects(['ship']),actions(['crosses']),location(moon),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(76, "A bird escapes through the space at snowy.", expected([subjects(['bird']),actions(['escapes']),location(space),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(77, "A dancer dances through the forest at clear.", expected([subjects(['dancer']),actions(['dances']),location(forest),weather(clear),style(vector),min_scene_count(5)])).
io_pair(78, "A robot jumps through the desert at night.", expected([subjects(['robot']),actions(['jumps']),location(desert),weather(night),style(rendered),min_scene_count(5)])).
io_pair(79, "A traveller approaches through the harbour at sunset.", expected([subjects(['traveller']),actions(['approaches']),location(harbour),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(80, "A pilot launches through the village at storm.", expected([subjects(['pilot']),actions(['launches']),location(village),weather(storm),style(vector),min_scene_count(5)])).
io_pair(81, "A cat runs through the city at rain.", expected([subjects(['cat']),actions(['runs']),location(city),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(82, "A tiger flies through the ocean at snowy.", expected([subjects(['tiger']),actions(['flies']),location(ocean),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(83, "A astronaut crosses through the palace at clear.", expected([subjects(['astronaut']),actions(['crosses']),location(palace),weather(clear),style(vector),min_scene_count(5)])).
io_pair(84, "A train escapes through the mountains at night.", expected([subjects(['train']),actions(['escapes']),location(mountains),weather(night),style(rendered),min_scene_count(5)])).
io_pair(85, "A ship dances through the moon at sunset.", expected([subjects(['ship']),actions(['dances']),location(moon),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(86, "A bird jumps through the space at storm.", expected([subjects(['bird']),actions(['jumps']),location(space),weather(storm),style(vector),min_scene_count(5)])).
io_pair(87, "A dancer approaches through the forest at rain.", expected([subjects(['dancer']),actions(['approaches']),location(forest),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(88, "A robot launches through the desert at snowy.", expected([subjects(['robot']),actions(['launches']),location(desert),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(89, "A traveller runs through the harbour at clear.", expected([subjects(['traveller']),actions(['runs']),location(harbour),weather(clear),style(vector),min_scene_count(5)])).
io_pair(90, "A pilot flies through the village at night.", expected([subjects(['pilot']),actions(['flies']),location(village),weather(night),style(rendered),min_scene_count(5)])).
io_pair(91, "A cat crosses through the city at sunset.", expected([subjects(['cat']),actions(['crosses']),location(city),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(92, "A tiger escapes through the ocean at storm.", expected([subjects(['tiger']),actions(['escapes']),location(ocean),weather(storm),style(vector),min_scene_count(5)])).
io_pair(93, "A astronaut dances through the palace at rain.", expected([subjects(['astronaut']),actions(['dances']),location(palace),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(94, "A train jumps through the mountains at snowy.", expected([subjects(['train']),actions(['jumps']),location(mountains),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(95, "A ship approaches through the moon at clear.", expected([subjects(['ship']),actions(['approaches']),location(moon),weather(clear),style(vector),min_scene_count(5)])).
io_pair(96, "A bird launches through the space at night.", expected([subjects(['bird']),actions(['launches']),location(space),weather(night),style(rendered),min_scene_count(5)])).
io_pair(97, "A dancer runs through the forest at sunset.", expected([subjects(['dancer']),actions(['runs']),location(forest),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(98, "A robot flies through the desert at storm.", expected([subjects(['robot']),actions(['flies']),location(desert),weather(storm),style(vector),min_scene_count(5)])).
io_pair(99, "A traveller crosses through the harbour at rain.", expected([subjects(['traveller']),actions(['crosses']),location(harbour),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(100, "A pilot escapes through the village at snowy.", expected([subjects(['pilot']),actions(['escapes']),location(village),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(101, "A cat dances through the city at clear.", expected([subjects(['cat']),actions(['dances']),location(city),weather(clear),style(vector),min_scene_count(5)])).
io_pair(102, "A tiger jumps through the ocean at night.", expected([subjects(['tiger']),actions(['jumps']),location(ocean),weather(night),style(rendered),min_scene_count(5)])).
io_pair(103, "A astronaut approaches through the palace at sunset.", expected([subjects(['astronaut']),actions(['approaches']),location(palace),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(104, "A train launches through the mountains at storm.", expected([subjects(['train']),actions(['launches']),location(mountains),weather(storm),style(vector),min_scene_count(5)])).
io_pair(105, "A ship runs through the moon at rain.", expected([subjects(['ship']),actions(['runs']),location(moon),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(106, "A bird flies through the space at snowy.", expected([subjects(['bird']),actions(['flies']),location(space),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(107, "A dancer crosses through the forest at clear.", expected([subjects(['dancer']),actions(['crosses']),location(forest),weather(clear),style(vector),min_scene_count(5)])).
io_pair(108, "A robot escapes through the desert at night.", expected([subjects(['robot']),actions(['escapes']),location(desert),weather(night),style(rendered),min_scene_count(5)])).
io_pair(109, "A traveller dances through the harbour at sunset.", expected([subjects(['traveller']),actions(['dances']),location(harbour),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(110, "A pilot jumps through the village at storm.", expected([subjects(['pilot']),actions(['jumps']),location(village),weather(storm),style(vector),min_scene_count(5)])).
io_pair(111, "A cat approaches through the city at rain.", expected([subjects(['cat']),actions(['approaches']),location(city),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(112, "A tiger launches through the ocean at snowy.", expected([subjects(['tiger']),actions(['launches']),location(ocean),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(113, "A astronaut runs through the palace at clear.", expected([subjects(['astronaut']),actions(['runs']),location(palace),weather(clear),style(vector),min_scene_count(5)])).
io_pair(114, "A train flies through the mountains at night.", expected([subjects(['train']),actions(['flies']),location(mountains),weather(night),style(rendered),min_scene_count(5)])).
io_pair(115, "A ship crosses through the moon at sunset.", expected([subjects(['ship']),actions(['crosses']),location(moon),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(116, "A bird escapes through the space at storm.", expected([subjects(['bird']),actions(['escapes']),location(space),weather(storm),style(vector),min_scene_count(5)])).
io_pair(117, "A dancer dances through the forest at rain.", expected([subjects(['dancer']),actions(['dances']),location(forest),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(118, "A robot jumps through the desert at snowy.", expected([subjects(['robot']),actions(['jumps']),location(desert),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(119, "A traveller approaches through the harbour at clear.", expected([subjects(['traveller']),actions(['approaches']),location(harbour),weather(clear),style(vector),min_scene_count(5)])).
io_pair(120, "A pilot launches through the village at night.", expected([subjects(['pilot']),actions(['launches']),location(village),weather(night),style(rendered),min_scene_count(5)])).
io_pair(121, "A cat runs through the city at sunset.", expected([subjects(['cat']),actions(['runs']),location(city),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(122, "A tiger flies through the ocean at storm.", expected([subjects(['tiger']),actions(['flies']),location(ocean),weather(storm),style(vector),min_scene_count(5)])).
io_pair(123, "A astronaut crosses through the palace at rain.", expected([subjects(['astronaut']),actions(['crosses']),location(palace),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(124, "A train escapes through the mountains at snowy.", expected([subjects(['train']),actions(['escapes']),location(mountains),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(125, "A ship dances through the moon at clear.", expected([subjects(['ship']),actions(['dances']),location(moon),weather(clear),style(vector),min_scene_count(5)])).
io_pair(126, "A bird jumps through the space at night.", expected([subjects(['bird']),actions(['jumps']),location(space),weather(night),style(rendered),min_scene_count(5)])).
io_pair(127, "A dancer approaches through the forest at sunset.", expected([subjects(['dancer']),actions(['approaches']),location(forest),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(128, "A robot launches through the desert at storm.", expected([subjects(['robot']),actions(['launches']),location(desert),weather(storm),style(vector),min_scene_count(5)])).
io_pair(129, "A traveller runs through the harbour at rain.", expected([subjects(['traveller']),actions(['runs']),location(harbour),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(130, "A pilot flies through the village at snowy.", expected([subjects(['pilot']),actions(['flies']),location(village),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(131, "A cat crosses through the city at clear.", expected([subjects(['cat']),actions(['crosses']),location(city),weather(clear),style(vector),min_scene_count(5)])).
io_pair(132, "A tiger escapes through the ocean at night.", expected([subjects(['tiger']),actions(['escapes']),location(ocean),weather(night),style(rendered),min_scene_count(5)])).
io_pair(133, "A astronaut dances through the palace at sunset.", expected([subjects(['astronaut']),actions(['dances']),location(palace),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(134, "A train jumps through the mountains at storm.", expected([subjects(['train']),actions(['jumps']),location(mountains),weather(storm),style(vector),min_scene_count(5)])).
io_pair(135, "A ship approaches through the moon at rain.", expected([subjects(['ship']),actions(['approaches']),location(moon),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(136, "A bird launches through the space at snowy.", expected([subjects(['bird']),actions(['launches']),location(space),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(137, "A dancer runs through the forest at clear.", expected([subjects(['dancer']),actions(['runs']),location(forest),weather(clear),style(vector),min_scene_count(5)])).
io_pair(138, "A robot flies through the desert at night.", expected([subjects(['robot']),actions(['flies']),location(desert),weather(night),style(rendered),min_scene_count(5)])).
io_pair(139, "A traveller crosses through the harbour at sunset.", expected([subjects(['traveller']),actions(['crosses']),location(harbour),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(140, "A pilot escapes through the village at storm.", expected([subjects(['pilot']),actions(['escapes']),location(village),weather(storm),style(vector),min_scene_count(5)])).
io_pair(141, "A cat dances through the city at rain.", expected([subjects(['cat']),actions(['dances']),location(city),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(142, "A tiger jumps through the ocean at snowy.", expected([subjects(['tiger']),actions(['jumps']),location(ocean),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(143, "A astronaut approaches through the palace at clear.", expected([subjects(['astronaut']),actions(['approaches']),location(palace),weather(clear),style(vector),min_scene_count(5)])).
io_pair(144, "A train launches through the mountains at night.", expected([subjects(['train']),actions(['launches']),location(mountains),weather(night),style(rendered),min_scene_count(5)])).
io_pair(145, "A ship runs through the moon at sunset.", expected([subjects(['ship']),actions(['runs']),location(moon),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(146, "A bird flies through the space at storm.", expected([subjects(['bird']),actions(['flies']),location(space),weather(storm),style(vector),min_scene_count(5)])).
io_pair(147, "A dancer crosses through the forest at rain.", expected([subjects(['dancer']),actions(['crosses']),location(forest),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(148, "A robot escapes through the desert at snowy.", expected([subjects(['robot']),actions(['escapes']),location(desert),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(149, "A traveller dances through the harbour at clear.", expected([subjects(['traveller']),actions(['dances']),location(harbour),weather(clear),style(vector),min_scene_count(5)])).
io_pair(150, "A pilot jumps through the village at night.", expected([subjects(['pilot']),actions(['jumps']),location(village),weather(night),style(rendered),min_scene_count(5)])).
io_pair(151, "A cat approaches through the city at sunset.", expected([subjects(['cat']),actions(['approaches']),location(city),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(152, "A tiger launches through the ocean at storm.", expected([subjects(['tiger']),actions(['launches']),location(ocean),weather(storm),style(vector),min_scene_count(5)])).
io_pair(153, "A astronaut runs through the palace at rain.", expected([subjects(['astronaut']),actions(['runs']),location(palace),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(154, "A train flies through the mountains at snowy.", expected([subjects(['train']),actions(['flies']),location(mountains),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(155, "A ship crosses through the moon at clear.", expected([subjects(['ship']),actions(['crosses']),location(moon),weather(clear),style(vector),min_scene_count(5)])).
io_pair(156, "A bird escapes through the space at night.", expected([subjects(['bird']),actions(['escapes']),location(space),weather(night),style(rendered),min_scene_count(5)])).
io_pair(157, "A dancer dances through the forest at sunset.", expected([subjects(['dancer']),actions(['dances']),location(forest),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(158, "A robot jumps through the desert at storm.", expected([subjects(['robot']),actions(['jumps']),location(desert),weather(storm),style(vector),min_scene_count(5)])).
io_pair(159, "A traveller approaches through the harbour at rain.", expected([subjects(['traveller']),actions(['approaches']),location(harbour),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(160, "A pilot launches through the village at snowy.", expected([subjects(['pilot']),actions(['launches']),location(village),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(161, "A cat runs through the city at clear.", expected([subjects(['cat']),actions(['runs']),location(city),weather(clear),style(vector),min_scene_count(5)])).
io_pair(162, "A tiger flies through the ocean at night.", expected([subjects(['tiger']),actions(['flies']),location(ocean),weather(night),style(rendered),min_scene_count(5)])).
io_pair(163, "A astronaut crosses through the palace at sunset.", expected([subjects(['astronaut']),actions(['crosses']),location(palace),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(164, "A train escapes through the mountains at storm.", expected([subjects(['train']),actions(['escapes']),location(mountains),weather(storm),style(vector),min_scene_count(5)])).
io_pair(165, "A ship dances through the moon at rain.", expected([subjects(['ship']),actions(['dances']),location(moon),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(166, "A bird jumps through the space at snowy.", expected([subjects(['bird']),actions(['jumps']),location(space),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(167, "A dancer approaches through the forest at clear.", expected([subjects(['dancer']),actions(['approaches']),location(forest),weather(clear),style(vector),min_scene_count(5)])).
io_pair(168, "A robot launches through the desert at night.", expected([subjects(['robot']),actions(['launches']),location(desert),weather(night),style(rendered),min_scene_count(5)])).
io_pair(169, "A traveller runs through the harbour at sunset.", expected([subjects(['traveller']),actions(['runs']),location(harbour),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(170, "A pilot flies through the village at storm.", expected([subjects(['pilot']),actions(['flies']),location(village),weather(storm),style(vector),min_scene_count(5)])).
io_pair(171, "A cat crosses through the city at rain.", expected([subjects(['cat']),actions(['crosses']),location(city),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(172, "A tiger escapes through the ocean at snowy.", expected([subjects(['tiger']),actions(['escapes']),location(ocean),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(173, "A astronaut dances through the palace at clear.", expected([subjects(['astronaut']),actions(['dances']),location(palace),weather(clear),style(vector),min_scene_count(5)])).
io_pair(174, "A train jumps through the mountains at night.", expected([subjects(['train']),actions(['jumps']),location(mountains),weather(night),style(rendered),min_scene_count(5)])).
io_pair(175, "A ship approaches through the moon at sunset.", expected([subjects(['ship']),actions(['approaches']),location(moon),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(176, "A bird launches through the space at storm.", expected([subjects(['bird']),actions(['launches']),location(space),weather(storm),style(vector),min_scene_count(5)])).
io_pair(177, "A dancer runs through the forest at rain.", expected([subjects(['dancer']),actions(['runs']),location(forest),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(178, "A robot flies through the desert at snowy.", expected([subjects(['robot']),actions(['flies']),location(desert),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(179, "A traveller crosses through the harbour at clear.", expected([subjects(['traveller']),actions(['crosses']),location(harbour),weather(clear),style(vector),min_scene_count(5)])).
io_pair(180, "A pilot escapes through the village at night.", expected([subjects(['pilot']),actions(['escapes']),location(village),weather(night),style(rendered),min_scene_count(5)])).
io_pair(181, "A cat dances through the city at sunset.", expected([subjects(['cat']),actions(['dances']),location(city),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(182, "A tiger jumps through the ocean at storm.", expected([subjects(['tiger']),actions(['jumps']),location(ocean),weather(storm),style(vector),min_scene_count(5)])).
io_pair(183, "A astronaut approaches through the palace at rain.", expected([subjects(['astronaut']),actions(['approaches']),location(palace),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(184, "A train launches through the mountains at snowy.", expected([subjects(['train']),actions(['launches']),location(mountains),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(185, "A ship runs through the moon at clear.", expected([subjects(['ship']),actions(['runs']),location(moon),weather(clear),style(vector),min_scene_count(5)])).
io_pair(186, "A bird flies through the space at night.", expected([subjects(['bird']),actions(['flies']),location(space),weather(night),style(rendered),min_scene_count(5)])).
io_pair(187, "A dancer crosses through the forest at sunset.", expected([subjects(['dancer']),actions(['crosses']),location(forest),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(188, "A robot escapes through the desert at storm.", expected([subjects(['robot']),actions(['escapes']),location(desert),weather(storm),style(vector),min_scene_count(5)])).
io_pair(189, "A traveller dances through the harbour at rain.", expected([subjects(['traveller']),actions(['dances']),location(harbour),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(190, "A pilot jumps through the village at snowy.", expected([subjects(['pilot']),actions(['jumps']),location(village),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(191, "A cat approaches through the city at clear.", expected([subjects(['cat']),actions(['approaches']),location(city),weather(clear),style(vector),min_scene_count(5)])).
io_pair(192, "A tiger launches through the ocean at night.", expected([subjects(['tiger']),actions(['launches']),location(ocean),weather(night),style(rendered),min_scene_count(5)])).
io_pair(193, "A astronaut runs through the palace at sunset.", expected([subjects(['astronaut']),actions(['runs']),location(palace),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(194, "A train flies through the mountains at storm.", expected([subjects(['train']),actions(['flies']),location(mountains),weather(storm),style(vector),min_scene_count(5)])).
io_pair(195, "A ship crosses through the moon at rain.", expected([subjects(['ship']),actions(['crosses']),location(moon),weather(rain),style(rendered),min_scene_count(5)])).
io_pair(196, "A bird escapes through the space at snowy.", expected([subjects(['bird']),actions(['escapes']),location(space),weather(snowy),style(pixel),min_scene_count(5)])).
io_pair(197, "A dancer dances through the forest at clear.", expected([subjects(['dancer']),actions(['dances']),location(forest),weather(clear),style(vector),min_scene_count(5)])).
io_pair(198, "A robot jumps through the desert at night.", expected([subjects(['robot']),actions(['jumps']),location(desert),weather(night),style(rendered),min_scene_count(5)])).
io_pair(199, "A traveller approaches through the harbour at sunset.", expected([subjects(['traveller']),actions(['approaches']),location(harbour),weather(sunset),style(pixel),min_scene_count(5)])).
io_pair(200, "A pilot launches through the village at storm.", expected([subjects(['pilot']),actions(['launches']),location(village),weather(storm),style(vector),min_scene_count(5)])).
